export default {
  Base: "/api",
  Health: "/health",
  Admin: {
    Base: "/admin",
    User: {
      Base: "/user",
      GetAllUsers: "/getAllUsers",
      GetUser: "/getUser",
      UpdateUserInfo: "/updateUserInfo",
      CreateUser: "/registerUser",
    },
    Lang: {
      Base: "/lang",
      GetAllLang: "/getAllLang",
      UpdateLang: "/updateLang",
      CreateLang: "/createLang",
    },
  },
  MetaData: {
    Base: "/metadata",
    AddAllMetaData: "/addAll",
    AddMetaData: "/add",
    GetMetadata: "/getMetadata",
  },
  Auth: {
    Base: "/auth",
    CheckUser: "/inquireUser",
    CreateUser: "/registerUser",
    DeletedUser: "/deleteUser",
    Login: "/login",
    Logout: "/logout",
  },
  Users: {
    Base: "/users",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
  },
  Notification: {
    Base: "/users",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
  },
  Messaging: {
    Base: "/users",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
  },
  Dashboard: {
    Base: "/users",
    Get: "/all",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
  },
  Bets: {
    Base: "/bets",
    placeBet: "/placebet",
    getAllBets: "/allbets",
    getBet: "/bet",
  },
} as const;
